### ISSUE TITLE
Doesn't work in Safari 10.0 (11602.1.50.0.10)

### ISSUE THREAD

**Issue by celkins** [esha/wsdemo#2]
Error Console shows:

```
[Error] TypeError: undefined is not an object (evaluating 'd.style.textContent="[x-repeat] { display: none }"')
	(anonymous function) (vendor.js:5:7200)
	Global Code (vendor.js:5:7493)
```
and
```
[Error] TypeError: undefined is not a constructor (evaluating 'new e')
	(anonymous function) (main.js:1:6397)
	Global Code (main.js:1:14859)
```

**Comment by nbubna** [comment]
Apparently, Safari/WebKit/whoever have added an HTMLElement.prototype.append function that makes the domx-repeat library unhappy. Why they have added this and how it is different than the well-established HTMLElement.prototype.appendChild are mysteries. I've yet to find any spec or documentation for this DOM addition. But am i surprised that Apple would just do their own non-standard thing without explanation? No, not really.

Fix will be deployed shortly...
